import Theme from '@/components/context/Theme'
import './styles/globals.css'
import { inter } from '@/fonts';
import Footer from '@/components/footer';
export const metadata = {
  title: 'Todo List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className='md:text-[100%] text-[80%]'>
      <body className={
        `${inter.className}
        h-screen
        bg-light-p
        dark:bg-dark-p
        flex
        flex-col
        `}>
        <Theme>
          {children}
          <Footer />
        </Theme>
      </body>
    </html>
  )
}
