import Theme from '@/components/ui/Theme'
import './styles/globals.css'
export const metadata = {
  title: 'Todo List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className='bg-light-p dark:bg-dark-p'>
        <Theme>
          {children}
        </Theme>
      </body>
    </html>
  )
}
